CREATE TABLE IF NOT EXISTS patient (
    patient_id BIGINT NOT NULL AUTO_INCREMENT,
    name       VARCHAR(150) NOT NULL,
    DOB        DATE NOT NULL,
    PRIMARY KEY (patient_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;