export const NAV_ITEMS = [
  {
    href: '/dashboard',
    label: 'Dashboard',
    icon: 'layout',
    group: 'Plan',
    desc: 'Transition readiness per patient: outstanding requirements, resources and handoff state.',
  },
  {
    href: '/patients',
    label: 'Patients',
    icon: 'activity',
    group: 'Clinical',
    desc: 'Search patients, view patient details and manage admissions.',
  },
  {
    href: '/facilities',
    label: 'Facilities',
    icon: 'home',
    group: 'Clinical',
    desc: 'Browse and register care facilities.',
  },
  {
    href: '/discharge-plans/new',
    match: '/discharge-plans',
    label: 'Discharge',
    icon: 'clipboard',
    group: 'Plan',
    desc: 'Plan a discharge, define what must be in place, and move it to ready.',
  },
  {
    href: '/resources',
    label: 'Resources',
    icon: 'box',
    group: 'Resources',
    desc: 'Browse beds, equipment and services, and see what is free in a time window.',
  },
  {
    href: '/allocations',
    label: 'Allocate',
    icon: 'trend',
    group: 'Resources',
    desc: 'Book a free resource for a requirement without double-booking, and complete or cancel bookings.',
  },
  {
    href: '/recovery',
    label: 'Recovery',
    icon: 'activity',
    group: 'Care',
    desc: 'Track a patient\'s continuing recovery episodes and the requirements tied to them.',
  },
  {
    href: '/handoffs',
    label: 'Handoffs',
    icon: 'send',
    group: 'Care',
    desc: 'Prepare, send and acknowledge the formal transfer of care to the next facility.',
  },
  {
    href: '/documents',
    label: 'Documents',
    icon: 'file',
    group: 'Care',
    desc: 'Register care documents, upload their text and control which ones are searchable.',
  },
  {
    href: '/search',
    label: 'Search',
    icon: 'search',
    group: 'Care',
    desc: 'Find the right passage by meaning, not exact keywords, with the source document shown.',
  },
  { href: '/doctors', label: 'Doctors', icon: 'activity', group: 'Clinical',
    desc: 'Register doctors and keep their specialisation and contact details current.' },
  { href: '/users', label: 'Users', icon: 'layout', roles: ['ADMIN'] },

];